### ISSUE TITLE
Suggesting change in WarehouseCalloutServiceTest.cls

### ISSUE THREAD

**Issue by unovikash** [Calega/ApexSpecialistSuperbadge#1]
Thank you for uploading this to Github. It helped me a lot with solving the challenge.

I have one suggestion in the Test class. It seems like you have added **Test.stopTest()** after the assertions. This was causing the test to fail as Salesforce executes the asynchronous tasks **after the stopTest()**. Hence, the assertions need to be just after the runWarehouseEquipmentSync().

`
Test.startTest();
Test.setMock(HttpCalloutMock.class, new WarehouseCalloutServiceMock());
WarehouseCalloutService.runWarehouseEquipmentSync();
Test.stopTest();
`

**Comment by Calega** [comment]
Thank you for bringing this up Unovikash!
I don't recall it failing when I tested a few months ago. I've tested it now, and it failed.
I'm committing the suggested changes. Cheers.
